name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: times-excel-reader

      - name: Install packages
        working-directory: times-excel-reader
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check code formatting
        working-directory: times-excel-reader
        run: |
          pre-commit install
          pre-commit run --all-files

      # ---------- Prepare ETSAP Demo models

      - uses: actions/checkout@v3
        with:
          repository: olejandro/demos-dd
          path: benchmarks/dd

      - uses: actions/checkout@v3
        with:
          repository: olejandro/demos-xlsx
          path: benchmarks/xlsx
          token: ${{ secrets.GH_PAT_DEMOS_XLSX }}

      # ---------- Prepare TIMES Ireland Model

      # We add this model as the directory `ireland` under `benchmarks/{xlsx,dd}/`
      # so that the run_benchmarks.py script runs this model too
      - uses: actions/checkout@v3
        with:
          repository: samwebster/times-ireland-model
          path: benchmarks/xlsx/Ireland

      - uses: actions/checkout@v3
        with:
          repository: olejandro/times-ireland-model_gams
          path: benchmarks/dd/Ireland

      # ---------- Run tool, check for regressions

      - name: Run tool on all benchmarks
        working-directory: times-excel-reader
        run: python utils/run_benchmarks.py ../benchmarks
