name: CI-demos

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:

jobs:
  demos-test:
    runs-on: ubuntu-latest

    steps:
      - name: Download demo files
        run: |
          wget -nv https://iea-etsap.org/demo-models/VEDA-TIMES%20Demo%20Models.zip
          unzip *.zip

      - name: Convert xls to xlsx
        run: |
          sudo apt install libreoffice-calc default-jre libreoffice-java-common
          find . -name "*.xls" -type f -printf "soffice --convert-to xlsx --outdir '%h' '%p'\n" | bash
          find . -name "*.xlsx"

      - uses: actions/checkout@v3
        with:
          path: times-excel-reader

      - name: Run tool
        working-directory: times-excel-reader
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python times_excel_reader.py --ground_truth_dir "" "../VEDA-TIMES Demo Models/ETSAP_DemoS_VFE/DemoS_001"
